### ISSUE TITLE
消息顺序问题

### ISSUE THREAD

**Issue by mbyzhang** [KruinWorks/KruinBriefingBot#2]
同时转发多条消息到自己的 Channel 里会导致显示在 KruinChannel 里的消息顺序出现错乱。

**Comment by Elepover** [comment]
也许可以通过消息 ID 来判断

**Comment by Elepover** [comment]
由于这样的处理会导致机器人消息处理结构大幅变动（参见[此处](https://github.com/KruinWorks/KruinBriefingBot/blob/1337dc6bc02ebe03eb3e71450d106516e1c5711b/KruinBriefingBot/Variables.vb#L65)）。
所以...
